<a href="https://colab.research.google.com/github/ivashenceva220495-beep/My_first_repository/blob/main/ML_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_%D1%81%D0%BE_%D0%B7%D0%B2%D0%B5%D0%B7%D0%B4%D0%BE%D1%87%D0%BA%D0%BE%D0%B9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Загружаем необходимые библиотеки

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

Загружаем данные (экспорт таблицы)

In [ ]:
# Загрузите данные из файла insurance.csv в переменную df
df = pd.read_csv('ML_ДЗ - Лист1-2.csv' , sep=',')

In [ ]:
df.head()

,категория,траты в позапрошлом месяце,траты в прошлом месяце,траты в текущем месяце,траты в следующем месяце
0,обучение,10000.0,5000.0,30000.0,50000.0
1,одежда,20000.0,5000.0,15000.0,10000.0
2,медицина,15000.0,20000.0,10000.0,15000.0

Смотрим статистику, что нет пропусков и отсутствующих значений

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   категория                   3 non-null      object
 1   траты в позапрошлом месяце  3 non-null      float64
 2   траты в прошлом месяце      3 non-null      float64
 3   траты в текущем месяце      3 non-null      float64
 4   траты в следующем месяце    3 non-null      float64
dtypes: float64(4), object(1)
memory usage: 248.0+ bytes

In [ ]:
df.describe()

,траты в позапрошлом месяце,траты в прошлом месяце,траты в текущем месяце,траты в следующем месяце
count,3.0,3.000000,3.000000,3.000000
mean,15000.0,10000.000000,18333.333333,25000.000000
std,5000.0,8660.254038,10408.329997,21794.494718
min,10000.0,5000.000000,10000.000000,10000.000000
25%,12500.0,5000.000000,12500.000000,12500.000000
50%,15000.0,5000.000000,15000.000000,15000.000000
75%,17500.0,12500.000000,22500.000000,32500.000000
max,20000.0,20000.000000,30000.000000,50000.000000

Преобразуем строковые данные

In [ ]:
#Заменяем категорию на числа
df['категория'] = df['категория'].map({'обучение':0, 'одежда':1, 'медицина':2})

In [ ]:
df.head()

,категория,траты в позапрошлом месяце,траты в прошлом месяце,траты в текущем месяце,траты в следующем месяце
0,0,10000.0,5000.0,30000.0,50000.0
1,1,20000.0,5000.0,15000.0,10000.0
2,2,15000.0,20000.0,10000.0,15000.0

Формируем признаки и целевую переменную

In [ ]:
df.columns

Index(['категория', 'траты в позапрошлом месяце', 'траты в прошлом месяце',
       'траты в текущем месяце', 'траты в следующем месяце'],
      dtype='object')

In [ ]:
X = df[['категория', 'траты в позапрошлом месяце', 'траты в прошлом месяце',
       'траты в текущем месяце']]
y = df['траты в следующем месяце']

In [ ]:
X

,категория,траты в позапрошлом месяце,траты в прошлом месяце,траты в текущем месяце
0,0,10000.0,5000.0,30000.0
1,1,20000.0,5000.0,15000.0
2,2,15000.0,20000.0,10000.0

In [ ]:
y

0    50000.0
1    10000.0
2    15000.0
Name: траты в следующем месяце, dtype: float64

Разделяем данные на выборки: выборка для обучения, выборка для проверки

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

In [ ]:
X_train

,категория,траты в позапрошлом месяце,траты в прошлом месяце,траты в текущем месяце
1,1,20000.0,5000.0,15000.0

In [ ]:
X_test

,категория,траты в позапрошлом месяце,траты в прошлом месяце,траты в текущем месяце
2,2,15000.0,20000.0,10000.0
0,0,10000.0,5000.0,30000.0

In [ ]:
y_train

1    10000.0
Name: траты в следующем месяце, dtype: float64

In [ ]:
y_test

2    15000.0
0    50000.0
Name: траты в следующем месяце, dtype: float64

Создаем и обучаем модель

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(X_train, y_train)

LinearRegression()

Получаем предсказание и оцениваем

In [ ]:
lr.predict(X_test)

array([10000., 10000.])

In [ ]:
# Оцените качество, при помощи метода mean_squared_error для тестовой выборки
mean_squared_error(y_test, lr.predict(X_test))

812500000.0

In [ ]:
mean_squared_error(y_train, lr.predict(X_train))

0.0

Делаем предсказание для одной категории

In [ ]:
data = [{
         'категория': 1,
         'траты в позапрошлом месяце': 20000,
         'траты в прошлом месяце': 15000,
         'траты в текущем месяце': 5000

}]

In [ ]:
df_category = pd.DataFrame(data)
df_category.head()

,категория,траты в позапрошлом месяце,траты в прошлом месяце,траты в текущем месяце
0,1,20000,15000,5000

In [ ]:
lr.predict(df_category)

array([10000.])