<a href="https://colab.research.google.com/github/ivashenceva220495-beep/My_first_repository/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22_%D0%94%D0%97_ML_%D0%A1%D0%B0%D0%BD%D0%B4%D1%8B%D0%B1%D0%B0%D0%B5%D0%B2%D0%B0_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Предсказываем стоимость мед страховки

## Загужаем необходимые библиотеки

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

## Загружаем данные

Собраны данные:
- age: возраст
- sex: пол
- bmi: индекс массы тела
- children: количество детей, охваченных медицинским страхованием / количество иждивенцев
- smoker: курение
- region: регион (northeast, southeast, southwest, northwest).
- charges: индивидуальные медицинские расходы (его и хотим предсказать)

In [ ]:
# Загрузите данные из файла insurance.csv в переменную df
df = pd.read_csv('insurance.csv' , sep=',')

In [ ]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## Смотрим статистику, что нет пропусков и отсуствующих значений

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

## Преобразуем строковые данные

In [ ]:
# Заменяем пол и курение на числа
df['sex']=df['sex'].map({'male':1, 'female':0})
df['smoker']=df['smoker'].map({'yes':1,'no':0})

In [ ]:
df.head()

   age  sex     bmi  children  smoker     region      charges
0   19    0  27.900         0       1  southwest  16884.92400
1   18    1  33.770         1       0  southeast   1725.55230
2   28    1  33.000         3       0  southeast   4449.46200
3   33    1  22.705         0       0  northwest  21984.47061
4   32    1  28.880         0       0  northwest   3866.85520

In [ ]:
# Заменяем регион на набор отдельных колонок (is_southwest, is_southeast и тп)
df = pd.get_dummies(df, columns=['region'])
df.head()

,age,sex,bmi,children,smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,16884.92400,0,0,0,1
1,18,1,33.770,1,0,1725.55230,0,0,1,0
2,28,1,33.000,3,0,4449.46200,0,0,1,0
3,33,1,22.705,0,0,21984.47061,0,1,0,0
4,32,1,28.880,0,0,3866.85520,0,1,0,0

In [ ]:
df.head()

,age,sex,bmi,children,smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,16884.92400,0,0,0,1
1,18,1,33.770,1,0,1725.55230,0,0,1,0
2,28,1,33.000,3,0,4449.46200,0,0,1,0
3,33,1,22.705,0,0,21984.47061,0,1,0,0
4,32,1,28.880,0,0,3866.85520,0,1,0,0

## Формируем признаки и целевую переменную

In [ ]:
## Сформируйте признаки и целевую переменную
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges',
       'region_northeast', 'region_northwest', 'region_southeast',
       'region_southwest'],
      dtype='object')

In [ ]:
X = df [['age', 'sex', 'bmi', 'children', 'smoker',
       'region_northeast', 'region_northwest', 'region_southeast',
       'region_southwest']]
y = df['charges']

In [ ]:
X

,age,sex,bmi,children,smoker,region_northeast,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,0,0,0,1
1,18,1,33.770,1,0,0,0,1,0
2,28,1,33.000,3,0,0,0,1,0
3,33,1,22.705,0,0,0,1,0,0
4,32,1,28.880,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...
1333,50,1,30.970,3,0,0,1,0,0
1334,18,0,31.920,0,0,1,0,0,0
1335,18,0,36.850,0,0,0,0,1,0
1336,21,0,25.800,0,0,0,0,0,1
1337,61,0,29.070,0,1,0,1,0,0

In [ ]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

## Разделяем данные на выборку для обучения/проверки

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
X_train

,age,sex,bmi,children,smoker,region_northeast,region_northwest,region_southeast,region_southwest
287,63,0,26.220,0,0,0,1,0,0
26,63,0,23.085,0,0,1,0,0,0
350,57,0,23.180,0,0,0,1,0,0
1173,38,1,29.260,2,0,0,1,0,0
761,23,1,35.200,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...
1265,64,1,23.760,0,1,0,0,1,0
393,49,1,31.350,1,0,1,0,0,0
232,19,0,17.800,0,0,0,0,0,1
391,19,0,37.430,0,0,0,1,0,0
1245,28,1,24.300,5,0,0,0,0,1

In [ ]:
X_test

,age,sex,bmi,children,smoker,region_northeast,region_northwest,region_southeast,region_southwest
1099,25,0,33.990,1,0,0,0,1,0
65,19,0,28.900,0,0,0,0,0,1
673,41,0,31.020,0,0,0,0,1,0
1165,35,0,26.125,0,0,1,0,0,0
222,32,1,30.800,3,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...
498,44,0,23.980,2,0,0,0,1,0
384,44,1,22.135,2,0,1,0,0,0
271,50,1,34.200,2,1,0,0,0,1
543,54,0,47.410,0,1,0,0,1,0
501,43,1,26.030,0,0,1,0,0,0

In [ ]:
y_train

287     14256.19280
26      14451.83515
350     11830.60720
1173     6457.84340
761      2416.95500
           ...
1265    26926.51440
393      9290.13950
232      1727.78500
391      2138.07070
1245     5615.36900
Name: charges, Length: 1070, dtype: float64

In [ ]:
y_test

1099     3227.12110
65       1743.21400
673      6185.32080
1165     5227.98875
222      5253.52400
           ...
498      8211.10020
384      8302.53565
271     42856.83800
543     63770.42801
501      6837.36870
Name: charges, Length: 268, dtype: float64

## Создаем и обучаем модель линейной регресии

In [ ]:
# Создайте и обучите модель
lr = LinearRegression()

In [ ]:
lr.fit(X_train, y_train)

LinearRegression()

## Получаем предсказание и оцениваем качество

In [ ]:
# Получите предсказание
lr.predict(X_test)

array([ 5402.74010183,  1476.1891673 ,  7955.15534305,  5900.22598135,
        7101.0628338 ,  4457.35987332, 14115.12695941,  6076.85572052,
        8351.48677982, 38231.03479386,  2664.3970151 , 30725.01609872,
        8406.58382779,  3509.31603406,  7311.48169282, 10672.60382015,
        5790.67321517, -2187.27029676,  8758.87389091, 17790.76886733,
        6352.15489391, 32846.087425  ,  3062.75300824,  8208.27316941,
       15667.10536527, 12841.87751567, 29794.33944469, 16242.22846744,
        6634.6931633 ,  6812.00099407,  4801.79348621, 27347.66463619,
       10229.04217056,  2515.51650748, -2219.08926541, 14788.42107539,
       36075.65126117, 35508.61415048, 12639.01194816, 16328.15521625,
       29458.66958207, 16272.88854081, 40470.80701688, 38523.18402726,
        7055.11158813, 32106.50223912,  9366.18065543, 31231.55470352,
       28003.95080041,  9405.0757114 , 13126.66719579, 10249.6313396 ,
       13728.02680973,  3778.29336354, 31382.91034631,  4804.13222422,
       16333.66081307,  9877.05660212, 31747.61038458, 13041.6084363 ,
        4907.97101414, 31016.8328293 , 36778.05627588, 30753.81230925,
       13087.79988736,  6705.04963712, 12838.57349444, 13185.84409133,
       11303.72522294,  7393.71451695, 13057.70585629,  5250.50736161,
        9213.76355765,  4618.60588953, 26271.53552993,  8649.57330432,
        1451.45981194, 10772.76207762, 10508.93150467, 39858.01950873,
        3107.75432981,  1488.45056283, 12416.85761449,  5348.43384089,
       17382.45361389,  6798.21616793,  1510.31413634, 11855.74338497,
       29144.51131749,  9254.44683771, 15913.4258873 , 10355.73131139,
       11407.03569028, 33296.88820361, 13372.84064901, 35200.39352829,
        8601.89908389, 31588.16590354,  8665.32260053, 14885.04643534,
        9999.34852029,  3653.52885595,  2754.52001219,  4906.54078595,
        7635.67293523,  1470.71129148,  4334.49043734,  6285.44097888,
        6135.58378473,  1685.27082803,  5753.07967089, 10213.66821874,
        4044.1682707 , 16895.32684937, 11229.36096106, 18266.76106499,
       35947.60711941,  -225.50640248,  8674.18156251,  9732.32793823,
       10734.11342019, 31456.3965972 ,  6711.98028522, 11094.8575155 ,
       27498.19070885,  1631.439616  ,  9201.82457296,  -844.19671333,
       12081.99533663, 13120.17000983, 27006.9346476 , 13999.55977951,
        -528.03535395,  5344.05659554, 12575.58674238, 39429.63367496,
        6444.60686984, 25438.20011471, 14916.46521716,  8785.25527768,
        3710.09410496, 11882.13857628,  3445.20121918,  3317.34143498,
       34077.45992833,  9267.9230104 , 10698.06762201,  6868.70796246,
       31460.1294533 , 12122.28350454, 11654.72973931,  5624.3911279 ,
        7483.43023031, 11776.07286491,  8611.46218971, 36398.06746576,
       33203.98173683,  2615.32649476, 10956.08718991,  3054.05193761,
        5401.11660278, 15299.88639021, 34006.87286186,  9152.60068521,
        9578.12517298, 31658.92374177, -1818.43901997, 12837.34171403,
        7651.89642253, 10687.74487023, 38406.8746045 ,  5626.86274419,
       11461.49460845, 13224.62707763,  5519.14024539,  7394.25457564,
        3109.01379821, 11240.27535537, 11287.05700397, 23203.77489919,
       32971.53052269,  8637.2064909 , 11493.85130566,  5922.33695722,
        1023.60820698,   356.53083719,  4735.4034663 , 16156.64463248,
        9147.52654123, 10791.16767983, 39228.91843134, 13496.88404128,
        8094.98754712, 18808.1899197 ,  -210.47571771,  1984.46888165,
        7372.93370082,   835.27125229, 17306.9195545 ,  3931.71792116,
       35052.54339482, 30139.08556395,  4957.20668301,  6836.9654315 ,
        3906.76724179,  3825.7693968 , 38473.70152673, 39410.67526216,
        2307.08405971, 32493.05815936, 12654.96844705, 14125.03393765,
       36712.4062493 , 33168.1800281 , 12857.38563673,  4684.70416668,
       13587.79882856, 10960.70823922,  6439.45127155,  2953.13410187,
       13812.85630055,  5262.5292512 ,  8720.2914997 ,  9933.89891842,
       10040.63700615, 18009.98640915, 15696.243985  ,  -890.41899277,
        3990.77303545,  3305.41974111, 28753.89500846, 10849.73148514,
       37797.75834819, 35981.07899145,  8146.24973667, 36460.38428541,
        6128.90000131,  8335.45840701, 32771.50300256,  6422.54913461,
        8490.27846627, -1639.05657178, 38951.36197425, 12334.8124512 ,
        7068.21162889, 26330.87208824, 28005.76003908, 14052.03577308,
        9453.31901446,  3466.29817476, 12372.39592923, 27487.08535276,
         513.25957781,  7794.97060808, 10050.01441735,  9201.58761466,
        -236.31975521, 12110.87102452, 16280.4103045 , 28245.88852279,
       11373.36734742, 11709.60495671,  6083.83521257,  7274.58130954,
        7840.76436083, 35837.89411977, 40588.43201647,  7911.9384983 ])

In [ ]:
# Оцените качество, при помощи метода mean_squared_error для тестовой выборки
mean_squared_error(y_test, lr.predict(X_test))

44070589.578941904

In [ ]:
mean_squared_error(y_train, lr.predict(X_train))

34711228.34880411

## Делаем предсказание для одного человека

In [ ]:
# Заполняем данные по конкретному человеку
data = [{
    "age": 20,
    "sex": 1,
    "bmi": 30,
    "children": 2,
    "smoker": 1,
    "region_northeast": 0,
    "region_northwest": 0,
    "region_southeast": 1,
    "region_southwest": 0
}]

In [ ]:
df_person = pd.DataFrame(data)
df_person.head()

,age,sex,bmi,children,smoker,region_northeast,region_northwest,region_southeast,region_southwest
0,20,1,30,2,1,0,0,1,0

In [ ]:
lr.predict(df_person)

array([26557.65787028])